name: NexusBlock
description: Just destroy the block
main: hyro.lib.Main
version: 0.2.3-DEV
api-version: 1.13
author: Hyro
softdepend:
  # Holograms
  - HolographicDisplays
  - DecentHolograms
  - Holograms
  - CMI

  # MultiWorld
  - Multiverse-Core
  - MultiWorld

commands:
  nexusblock:
    description: Setup/info
    aliases:
      - blocknexus