name: NexusBlock
description: Just destroy the block
main: hyro.lib.Main
version: 0.2.1
api-version: 1.13
author: Hyro
softdepend:
  - HolographicDisplays
  - DecentHolograms

commands:
  nexusblock:
    description: Setup/info
    aliases:
      - blocknexus