name: NexusBlock
description: Just destroy the block
main: hyro.lib.Main
version: 0.2.2
api-version: 1.13
author: Hyro
softdepend:
  - HolographicDisplays
  - DecentHolograms
  - Multiverse-Core
  - MultiWorld

commands:
  nexusblock:
    description: Setup/info
    aliases:
      - blocknexus